version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
    - 5.36.0
  - dependency-name: eslint
    versions:
    - 6.8.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
