# You can use any Docker image from Docker Hub or your own container registry
image: node:latest

pipelines:
  default:
    - step:
        script:  # Modify the commands below to build and test your repository.
          - npm --version
          - node --version
          - npm install
          - npm run lint
          - npm run test
          - npm run codecov
