name: Publish
on:
  release:
    types: [published]

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: install & build
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
